### ISSUE TITLE
Improve S3Store

### ISSUE THREAD

**Issue by twinGu** [meggart/Zarr.jl#11] opened 2019-04-26 10:31 UTC
Writing data to an S3 Storage as well as some way to parallelize downloading of data when requesting many chunks needs to be implemented.

**Comment by rabernat** [comment] 2020-09-26 14:51
I'm curious what would be needed to implement writing to the S3Store. Would this require changes to AWSCore? Or is it just an issue in Zarr.jl?

**Comment by visr** [comment] 2020-09-26 17:46
AWSCore is now deprecated in favor of https://github.com/JuliaCloud/AWS.jl. It auto generates the entire API, so it probably will have us covered here.

**Comment by meggart** [comment] 2020-10-02 07:49
The main reason for not covering this is that this is quite hard to test for me. I was experimenting a bit with running a minio server to test read/write to S3, but with the new AWS.jl we unfortunately made a step backwards in supporting non-AWS S3-compatible storage services (look here https://github.com/JuliaCloud/AWS.jl/blob/master/src/AWS.jl#L445 , the endpoint is hard-coded again). 

Maybe it is not necesary to depend on AWS.jl which aims to support the complete AWS API, if all we need is to make a few S3 requests. Basically we only need to make `GET`, `PUT`, and `HEAD` requests, which can be done using HTTP.jl alone. The only tricky part is signing the request, so I am thinking about making the function `_sign_aws4!` and `_sign_aws2` (https://github.com/JuliaCloud/AWS.jl/blob/master/src/AWS.jl#L183-L286) more generic, so that they don't necessarily operate on a `AWS.Request` but are passed the whole request data and metadata as single arguments. 

By making the requests directly through HTTP.jl we would have full control over the endpoint and would get rid of a dependency which has considerable load- and precompile time.

**Comment by rabernat** [comment] 2020-10-02 13:38
> with the new AWS.jl we unfortunately made a step backwards in supporting non-AWS S3-compatible storage services (look here https://github.com/JuliaCloud/AWS.jl/blob/master/src/AWS.jl#L445 , the endpoint is hard-coded again).

Is there an issue for this? There are so many S3-compatible object storage services out there (e.g. [wasabi](https://wasabi.com/), [OSN](https://www.openstoragenetwork.org/), etc.). It would be a shame if Julia users couldn't use these.

My experience from the python side, in projects like s3fs, gcsfs, etc., is that read-only access is pretty simple and can be coded easily with http, but write access involves so many extras (tokens, multipart uploads, etc.) that "rolling your own" is not advisable. Better for Julia devs to collaborate around one full-featured library for S3 access.

**Comment by meggart** [comment] 2020-10-05 07:46
> Better for Julia devs to collaborate around one full-featured library for S3 access.

I fully agree here and if there was a S3FS.jl package I would immediately use this one. I think the problem is that AWS.jl simply has a different scope and does not seem to be generic enough to support our use cases. 

On the other hand, @manics might want to comment on his experience using AWSS3.jl ? You had the same problem, trying to access minio. An alternative would be to call into a different programming language for now until Julia libraries mature. Does anyone know of an easy-to-use C library that supports basic S3 operations? Of course one could simply use s3fs through PyCall, but one of the initial goals of this package was that it is completely Python-free. Suggestions are welcome...

**Comment by visr** [comment] 2020-10-05 08:14
I commented on https://github.com/JuliaCloud/AWS.jl/issues/111. Hopefully the endpoint can be made configurable again.

> Maybe it is not necesary to depend on AWS.jl which aims to support the complete AWS API, if all we need is to make a few S3 requests.

I just timed loading AWS.jl in Julia 1.6, and it took 1.45 seconds, whereas HTTP.jl alone took 0.96 seconds. So I don't think it's a big extra burden.

**Comment by meggart** [comment] 2020-10-05 08:18
> I just timed loading AWS.jl in Julia 1.6, and it took 1.45 seconds, whereas HTTP.jl alone took 0.96 seconds. So I don't think it's a big extra burden.

This is good news. I remember there was a time during Julia 1.2 or 1.3 where loading AWSCore took much longer than that. Thanks for opening the issue as well.

**Comment by mattBrzezinski** [comment] 2020-10-05 14:18
> The main reason for not covering this is that this is quite hard to test for me. I was experimenting a bit with running a minio server to test read/write to S3, but with the new AWS.jl we unfortunately made a step backwards in supporting non-AWS S3-compatible storage services (look here https://github.com/JuliaCloud/AWS.jl/blob/master/src/AWS.jl#L445 , the endpoint is hard-coded again).

I'm actively working on `AWS.jl`, this was an oversight on my part since I had forgotten that non-AWS S3 backed storage was a thing. I can introduce some way to use a different service provider for this some time shortly.

> I think the problem is that AWS.jl simply has a different scope and does not seem to be generic enough to support our use cases.

The intention behind `AWS.jl` was to essentially be `AWSCore.jl`, with a few more user friendly cases:

1) To have nicer high-level functions similar to service specific packages such as `AWSS3.jl` where required parameters are defined in each function definition, and all documentation so users don't need to read through pages of AWS Docs to use them.

2) To have autogeneration to give end-users the ability to use the newest services

It does this by basing all definitions off of [aws/aws-sdk-js](https://github.com/aws/aws-sdk-js/tree/master/apis). However things such as an S3 service provider are not defined in the [api definition](https://twitter.com/shitoberfest), and some of this code was brought over from `AWSCore.jl`.

**Comment by mattBrzezinski** [comment] 2020-10-05 15:24
Fix for this is here: https://github.com/JuliaCloud/AWS.jl/pull/211

**Comment by meggart** [comment] 2020-10-06 12:32
Ok, this is great to hear. Another thing that probably got lost during the transition is the possibility to do unsigned requests to public datasets, i.e. to allow `creds==nothing` and then in here https://github.com/JuliaCloud/AWS.jl/blob/master/src/AWS.jl#L351 do something like `aws.creds === nothing || _sign!(aws, request)`. SHall I open an issue at AWS.jl or make a PR for this?

**Comment by mattBrzezinski** [comment] 2020-10-06 15:16
> Ok, this is great to hear. Another thing that probably got lost during the transition is the possibility to do unsigned requests to public datasets, i.e. to allow `creds==nothing` and then in here https://github.com/JuliaCloud/AWS.jl/blob/master/src/AWS.jl#L351 do something like `aws.creds === nothing || _sign!(aws, request)`. SHall I open an issue at AWS.jl or make a PR for this?

All PRs in `AWS.jl` are welcome! If you don't want to make them yourself I can update it however I'm quite busy with non-open source software currently so it will be delayed.

**Comment by meggart** [comment] 2020-10-07 13:46
FYI I have created a PR at AWS.jl which would give us quite some flexibility in supporting different backends.

**Comment by meggart** [comment] 2021-04-08 08:11
I think we can close this now. S3Store now supports the full storage interface including read and write and this is all tested in CI through Minio.jl. Of course, having write unit tests for AWS would be nice to have, but probably not worth the additional costs/effort.

**Closed by meggart** 2021-04-08 08:11 UTC
